macro(sc_gen_examples)

set(_example_dir "example_null")

if (_backend_upper STREQUAL "SDL3_OPENGL3")
  set(_example_dir "example_sdl3_opengl3")
elseif (_backend_upper STREQUAL "SDL3_VULKAN")
  set(_example_dir "example_sdl3_vulkan")
elseif (_backend_upper STREQUAL "SDL3_SDLGPU3")
  set(_example_dir "example_sdl3_sdlgpu3")
elseif (_backend_upper STREQUAL "SDL3_SDLRENDERER3")
  set(_example_dir "example_sdl3_sdlrenderer3")
elseif (_backend_upper STREQUAL "SDL2_OPENGL2")
  set(_example_dir "example_sdl2_opengl2")
elseif (_backend_upper STREQUAL "SDL2_OPENGL3")
  set(_example_dir "example_sdl2_opengl3")
elseif (_backend_upper STREQUAL "SDL2_DIRECTX11")
  set(_example_dir "example_sdl2_directx11")
elseif (_backend_upper STREQUAL "SDL2_SDLRENDERER2")
  set(_example_dir "example_sdl2_sdlrenderer2")
elseif (_backend_upper STREQUAL "SDL2_VULKAN")
  set(_example_dir "example_sdl2_vulkan")
elseif (_backend_upper STREQUAL "GLFW_OPENGL2")
  set(_example_dir "example_glfw_opengl2")
elseif (_backend_upper STREQUAL "GLFW_OPENGL3")
  set(_example_dir "example_glfw_opengl3")
elseif (_backend_upper STREQUAL "GLFW_VULKAN")
  set(_example_dir "example_glfw_vulkan")
elseif (_backend_upper STREQUAL "WIN32_DIRECTX9")
  set(_example_dir "example_win32_directx9")
elseif (_backend_upper STREQUAL "WIN32_DIRECTX10")
  set(_example_dir "example_win32_directx10")
elseif (_backend_upper STREQUAL "WIN32_DIRECTX11")
  set(_example_dir "example_win32_directx11")
elseif (_backend_upper STREQUAL "WIN32_DIRECTX12")
  set(_example_dir "example_win32_directx12")
elseif (_backend_upper STREQUAL "WIN32_OPENGL3")
  set(_example_dir "example_win32_opengl3")
elseif (_backend_upper STREQUAL "WIN32_VULKAN")
  set(_example_dir "example_win32_vulkan")
elseif (_backend_upper STREQUAL "APPLE_METAL")
  set(_example_dir "example_apple_metal")
elseif (_backend_upper STREQUAL "APPLE_OPENGL2")
  set(_example_dir "example_apple_opengl2")  
endif()


set(_example_full_dir "${IMGUI_DIR}/examples/${_example_dir}")
if(EXISTS "${_example_full_dir}/main.cpp")
    set(_main_file "${_example_full_dir}/main.cpp")
elseif(EXISTS "${_example_full_dir}/main.mm")
    set(_main_file "${_example_full_dir}/main.mm")
endif()


if(_main_file)
    file(READ "${_main_file}" _main_content)
    string(REPLACE "int main(" "int main_impl(" _main_content "${_main_content}")
    get_filename_component(_main_file_ext ${_main_file} LAST_EXT)
    set(_example_source "${CMAKE_BINARY_DIR}/src/example/${_example_dir}${_main_file_ext}")
    file(WRITE ${_example_source} "${_main_content}")
endif()

unset(_main_content)
unset(_main_file)
unset(_example_dir)
unset(_example_full_dir)
endmacro(sc_gen_examples)
